version: '3.8'

services:

    uniapp:
       # build: uniapp
        image: askavin2000/sprint1app:jdk11
        ports:
        - 8484:8484

    postgres:
        image: postgres:14.5
        ports:
        - 5432:5432

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: sprint1demo


